let state={settings:{},features:{},events:[],slots:[],tables:[],contacts:[],selectedEvent:null,selectedSlot:null,selectedTable:null};
async function api(action,payload={}){const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,storeId:STORE_ID,...payload})});return res.json();}
function openMenu(){document.getElementById('sidebar').classList.add('open');document.getElementById('overlay').classList.add('show')}function closeMenu(){document.getElementById('sidebar').classList.remove('open');document.getElementById('overlay').classList.remove('show')}
document.getElementById('menuBtn').onclick=openMenu;document.getElementById('overlay').onclick=closeMenu;
function money(n){return Number(n||0).toLocaleString('th-TH')}
async function init(){try{const data=await api('publicBootstrap');state={...state,...data};renderSettings();renderEvents();renderSlots();renderZones();renderTables();renderContacts()}catch(e){alert('เชื่อมต่อระบบไม่สำเร็จ กรุณาตรวจสอบ API_URL')}}
function renderSettings(){const name=state.settings.store_name||'Table Booking';document.getElementById('brandName').textContent=name;document.getElementById('sideBrand').textContent=name;document.getElementById('heroTitle').textContent=name}
function renderEvents(){const box=document.getElementById('eventList');box.innerHTML='';state.events.forEach(ev=>{const div=document.createElement('div');div.className='card';div.innerHTML=`<h3>${ev.EventNameTH||ev.EventNameEN}</h3><p>${ev.StartDate||''} ${ev.StartTime||''}</p><button class="btn btn-primary btn-full">เลือกอีเวนต์</button>`;div.querySelector('button').onclick=()=>{state.selectedEvent=ev.EventID;renderSlots();location.hash='booking'};box.appendChild(div)});if(state.events[0]&&!state.selectedEvent)state.selectedEvent=state.events[0].EventID}
function renderSlots(){const box=document.getElementById('slotList');box.innerHTML='';state.slots.filter(s=>!state.selectedEvent||s.EventID===state.selectedEvent).forEach(s=>{const b=document.createElement('button');b.className='chip';b.textContent=s.SlotLabel||s.StartTime;b.onclick=()=>{state.selectedSlot=s.SlotID;[...box.children].forEach(x=>x.classList.remove('active'));b.classList.add('active');refreshAvailability()};box.appendChild(b)})}
function renderZones(){const box=document.getElementById('zoneFilters');box.innerHTML='<button class="chip active">ทั้งหมด</button>'}
function tableClass(t){if(t.Status==='booked')return 'status-booked';if(t.Status==='hold')return 'status-hold';if(t.Status==='disabled')return 'status-disabled';if(String(t.ZoneID||'').includes('VIP'))return 'status-vip';return 'status-available'}
function renderTables(){const map=document.getElementById('tableMap');map.innerHTML='';state.tables.forEach(t=>{const el=document.createElement('div');el.className=`table-item ${t.Shape==='round'?'table-round':''} ${tableClass(t)}`;el.style.left=(Number(t.X)||20)+'px';el.style.top=(Number(t.Y)||20)+'px';el.style.width=(Number(t.Width)||70)+'px';el.style.height=(Number(t.Height)||70)+'px';el.textContent=t.TableName;el.onclick=()=>showTable(t);map.appendChild(el)})}
function showTable(t){if(['booked','disabled'].includes(t.Status))return;state.selectedTable=t;document.getElementById('selectedTableName').textContent='โต๊ะ '+t.TableName;document.getElementById('selectedTableInfo').textContent=`${t.Seats} ที่นั่ง | ราคา ${money(t.BasePrice)} บาท | ขั้นต่ำ ${money(t.MinimumSpend)} บาท`;document.getElementById('tableSheet').classList.add('open')}
document.getElementById('selectTableBtn').onclick=()=>{document.getElementById('tableSheet').classList.remove('open');alert('เลือก '+state.selectedTable.TableName+' แล้ว')}
async function refreshAvailability(){const date=document.getElementById('bookingDate').value;if(!date||!state.selectedSlot)return;const data=await api('getAvailability',{eventId:state.selectedEvent,slotId:state.selectedSlot,bookingDate:date});state.tables=data.tables||state.tables;renderTables()}
document.getElementById('submitBooking').onclick=async()=>{if(!state.selectedTable)return alert('กรุณาเลือกโต๊ะ');const payload={eventId:state.selectedEvent,slotId:state.selectedSlot,tableId:state.selectedTable.TableID,bookingDate:document.getElementById('bookingDate').value,firstName:firstName.value,lastName:lastName.value,phone:phone.value,email:email.value,guests:guests.value,note:note.value};const res=await api('createBooking',payload);if(res.success){alert('จองสำเร็จ Booking ID: '+res.bookingId);location.reload()}else alert(res.message||'จองไม่สำเร็จ')}
function renderContacts(){const box=document.getElementById('contactChannels');box.innerHTML='';state.contacts.filter(c=>c.Active===true||c.Active==='TRUE').forEach(c=>{const a=document.createElement('a');a.className='btn btn-primary btn-full';a.href=c.URL||'#';a.target='_blank';a.textContent=c.ChannelName;box.appendChild(a)})}
init();
